parameters:
    example_one.operator_price_modifier: 50

services:
#    example_one.example:
#        class: ExampleOneBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


